#!/usr/bin/env python
# utils/build-script - The ultimate tool for building Swift -----*- python -*-
#
# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2016 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See http://swift.org/LICENSE.txt for license information
# See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
#
# ----------------------------------------------------------------------------
#
# swift_build_support/__main__.py launcher.
#
# ----------------------------------------------------------------------------

import os
import sys


os.environ["PYTHONPATH"] = (
        os.path.join(os.path.dirname(__file__), 'swift_build_support'))
os.execvpe('python',
           ['python', '-B', '-m', 'swift_build_support'] + sys.argv,
           os.environ)
